'use client';

import { useEffect, useState, useRef } from 'react';
import Link from 'next/link';

function useInView(threshold = 0.15) {
  const ref = useRef<HTMLDivElement>(null);
  const [visible, setVisible] = useState(false);
  useEffect(() => {
    const el = ref.current;
    if (!el) return;
    const obs = new IntersectionObserver(
      ([e]) => { if (e.isIntersecting) { setVisible(true); obs.disconnect(); } },
      { threshold }
    );
    obs.observe(el);
    return () => obs.disconnect();
  }, [threshold]);
  return { ref, visible };
}

export default function LandingPage() {
  const [mounted, setMounted] = useState(false);
  const hero = useInView(0.1);
  const powered = useInView();
  const features = useInView(0.08);
  const steps = useInView(0.08);
  const mockup = useInView(0.1);
  const africa = useInView();

  useEffect(() => { setMounted(true); }, []);

  return (
    <div className={`lr ${mounted ? 'lr--ready' : ''}`}>
      <style jsx global>{`
@import url('https://fonts.googleapis.com/css2?family=DM+Sans:opsz,wght@9..40,300;9..40,400;9..40,500;9..40,600;9..40,700;9..40,800&family=Instrument+Serif:ital@0;1&display=swap');
:root{--bg:#FAFBFE;--bg2:#F1F4F9;--bg3:#fff;--v:#6366F1;--v2:#818CF8;--v3:#C7D2FE;--v-bg:#EEF2FF;--o:#F97316;--o2:#FB923C;--o-bg:#FFF7ED;--g:#10B981;--g2:#34D399;--g-bg:#ECFDF5;--b:#3B82F6;--b-bg:#EFF6FF;--t1:#1E293B;--t2:#64748B;--t3:#94A3B8;--border:#E2E8F0;--bh:rgba(99,102,241,.25);--gv:rgba(99,102,241,.12)}
*{margin:0;padding:0;box-sizing:border-box}html{scroll-behavior:smooth}body{background:var(--bg);color:var(--t1);font-family:'DM Sans',-apple-system,sans-serif;overflow-x:hidden;-webkit-font-smoothing:antialiased}
.lr{opacity:0;transition:opacity .5s}.lr--ready{opacity:1}
.reveal{opacity:0;transform:translateY(30px);transition:opacity .7s cubic-bezier(.16,1,.3,1),transform .7s cubic-bezier(.16,1,.3,1)}.reveal.in{opacity:1;transform:translateY(0)}.reveal-d1{transition-delay:.1s}.reveal-d2{transition-delay:.2s}.reveal-d3{transition-delay:.3s}.reveal-d4{transition-delay:.4s}.reveal-d5{transition-delay:.5s}.reveal-d6{transition-delay:.6s}
.nav{position:fixed;top:0;left:0;right:0;z-index:100;padding:1rem 2rem;display:flex;justify-content:space-between;align-items:center;backdrop-filter:blur(20px) saturate(1.2);background:rgba(250,251,254,.85);border-bottom:1px solid var(--border)}.nav-left{display:flex;align-items:center;gap:.6rem;text-decoration:none}.nav-mark{width:32px;height:32px;border-radius:8px;background:linear-gradient(135deg,var(--v),#7C3AED);display:grid;place-items:center;font-size:14px;font-weight:800;color:#fff;box-shadow:0 2px 12px var(--gv)}.nav-word{font-weight:700;font-size:1.05rem;color:var(--t1)}.nav-mid{display:flex;gap:2.5rem}.nav-mid a{color:var(--t2);text-decoration:none;font-size:.85rem;font-weight:500;transition:color .2s}.nav-mid a:hover{color:var(--t1)}.nav-go{display:inline-flex;align-items:center;gap:.4rem;background:var(--v);color:#fff;padding:.55rem 1.4rem;border-radius:100px;font-size:.85rem;font-weight:600;text-decoration:none;transition:all .25s;box-shadow:0 2px 16px var(--gv)}.nav-go:hover{transform:translateY(-1px);box-shadow:0 4px 24px var(--gv);background:#5558E6}
.hero{position:relative;min-height:100vh;display:flex;flex-direction:column;justify-content:center;align-items:center;text-align:center;padding:7rem 2rem 4rem;overflow:hidden}.hero-pattern{position:absolute;inset:0;background-image:radial-gradient(circle at 1px 1px,rgba(99,102,241,.06) 1px,transparent 0);background-size:40px 40px;mask-image:radial-gradient(ellipse 60% 50% at 50% 40%,black 20%,transparent 100%)}.hero-glow1{position:absolute;width:600px;height:600px;border-radius:50%;background:var(--v);filter:blur(180px);opacity:.06;top:-10%;left:15%}.hero-glow2{position:absolute;width:500px;height:500px;border-radius:50%;background:var(--o);filter:blur(180px);opacity:.04;bottom:0;right:10%}
.hero-chip{display:inline-flex;align-items:center;gap:.5rem;padding:.45rem 1.1rem;border-radius:100px;background:var(--o-bg);border:1px solid rgba(249,115,22,.15);font-size:.78rem;font-weight:600;color:var(--o);margin-bottom:2rem}.hero-chip-dot{width:6px;height:6px;border-radius:50%;background:var(--o);animation:cp 2s ease-in-out infinite}@keyframes cp{0%,100%{opacity:1;transform:scale(1)}50%{opacity:.4;transform:scale(1.5)}}
.hero-h1{font-family:'Instrument Serif',serif;font-size:clamp(3rem,7.5vw,6rem);font-weight:400;line-height:1.05;letter-spacing:-.04em;max-width:850px;margin-bottom:1.5rem}.hero-h1 em{font-style:italic;background:linear-gradient(135deg,var(--v),var(--o),var(--g));-webkit-background-clip:text;-webkit-text-fill-color:transparent;background-clip:text}
.hero-p{font-size:clamp(.95rem,1.8vw,1.15rem);color:var(--t2);max-width:520px;line-height:1.7;margin-bottom:2.5rem}
.hero-btns{display:flex;gap:.75rem;flex-wrap:wrap;justify-content:center}.btn-main{display:inline-flex;align-items:center;gap:.5rem;background:var(--v);color:#fff;padding:.9rem 2.2rem;border-radius:100px;font-size:.95rem;font-weight:600;text-decoration:none;transition:all .3s;box-shadow:0 4px 20px var(--gv)}.btn-main:hover{transform:translateY(-2px);box-shadow:0 8px 30px var(--gv);background:#5558E6}.btn-ghost{display:inline-flex;align-items:center;gap:.5rem;background:var(--bg3);color:var(--t1);padding:.9rem 2.2rem;border-radius:100px;font-size:.95rem;font-weight:500;text-decoration:none;border:1px solid var(--border);transition:all .3s}.btn-ghost:hover{border-color:var(--bh);background:var(--v-bg);transform:translateY(-1px)}
.hero-metrics{display:flex;gap:3rem;margin-top:4rem;padding-top:3rem;border-top:1px solid var(--border)}.metric{text-align:center}.metric-val{font-family:'Instrument Serif',serif;font-size:2.2rem;font-weight:400}.metric-val.c-v{color:var(--v)}.metric-val.c-o{color:var(--o)}.metric-val.c-g{color:var(--g)}.metric-val.c-b{color:var(--b)}.metric-lbl{font-size:.65rem;text-transform:uppercase;letter-spacing:.14em;color:var(--t3);margin-top:.15rem;font-weight:600}
.logos{padding:3rem 2rem;border-top:1px solid var(--border);border-bottom:1px solid var(--border);background:var(--bg2)}.logos-label{font-size:.6rem;text-transform:uppercase;letter-spacing:.18em;color:var(--t3);text-align:center;margin-bottom:1.5rem;font-weight:700}.logos-row{display:flex;justify-content:center;align-items:center;gap:1.5rem;flex-wrap:wrap}.logo-pill{display:flex;align-items:center;gap:.5rem;padding:.45rem 1rem;border-radius:100px;border:1px solid var(--border);background:var(--bg3);transition:all .3s;box-shadow:0 1px 3px rgba(0,0,0,.04)}.logo-pill:hover{border-color:var(--bh);box-shadow:0 4px 12px var(--gv);transform:translateY(-1px)}.logo-dot{width:8px;height:8px;border-radius:50%}.logo-dot.d-o{background:var(--o)}.logo-dot.d-v{background:var(--v)}.logo-dot.d-g{background:var(--g)}.logo-dot.d-b{background:var(--b)}.logo-dot.d-y{background:#EAB308}.logo-name{font-size:.8rem;color:var(--t2);font-weight:500}
.feat{padding:6rem 2rem;max-width:1200px;margin:0 auto}.eyebrow{font-size:.65rem;text-transform:uppercase;letter-spacing:.18em;color:var(--v);text-align:center;margin-bottom:.5rem;font-weight:700}.sect-h{font-family:'Instrument Serif',serif;font-size:clamp(2rem,4vw,3rem);text-align:center;margin-bottom:.75rem;letter-spacing:-.03em;font-weight:400}.sect-p{text-align:center;color:var(--t2);max-width:460px;margin:0 auto 3.5rem;font-size:.95rem;line-height:1.6}.feat-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:1.25rem}.feat-card{background:var(--bg3);border:1px solid var(--border);border-radius:16px;padding:1.75rem;transition:all .35s}.feat-card:hover{border-color:var(--bh);transform:translateY(-4px);box-shadow:0 16px 48px rgba(0,0,0,.06)}.feat-emoji{font-size:1.6rem;margin-bottom:.75rem;display:block}.feat-name{font-size:1rem;font-weight:700;margin-bottom:.35rem}.feat-desc{font-size:.85rem;color:var(--t2);line-height:1.6}.feat-tag{display:inline-block;margin-top:.75rem;padding:.2rem .6rem;border-radius:100px;font-size:.6rem;font-weight:700;text-transform:uppercase;letter-spacing:.06em}.feat-tag.tag-v{background:var(--v-bg);color:var(--v)}.feat-tag.tag-o{background:var(--o-bg);color:var(--o)}.feat-tag.tag-g{background:var(--g-bg);color:var(--g)}.feat-tag.tag-b{background:var(--b-bg);color:var(--b)}
.mockup-sect{padding:4rem 2rem 5rem;max-width:1050px;margin:0 auto}.mockup-frame{background:var(--bg3);border:1px solid var(--border);border-radius:16px;overflow:hidden;box-shadow:0 20px 60px rgba(0,0,0,.07)}.mockup-bar{display:flex;align-items:center;gap:.5rem;padding:.65rem 1rem;background:var(--bg2);border-bottom:1px solid var(--border)}.mockup-dot{width:10px;height:10px;border-radius:50%}.mockup-dot.r{background:#EF4444}.mockup-dot.y{background:#EAB308}.mockup-dot.g{background:#22C55E}.mockup-url{flex:1;text-align:center;font-size:.7rem;color:var(--t3);font-weight:500}.mockup-body{display:grid;grid-template-columns:1fr 2fr;min-height:380px}.mock-sidebar{padding:1.25rem;border-right:1px solid var(--border);display:flex;flex-direction:column;gap:.75rem}.mock-widget{background:var(--bg);border:1px solid var(--border);border-radius:10px;padding:.85rem}.mock-widget-title{font-size:.7rem;font-weight:700;margin-bottom:.5rem;display:flex;align-items:center;gap:.35rem}.mock-skill-row{display:flex;flex-wrap:wrap;gap:.25rem;margin-top:.35rem}.mock-skill{padding:.15rem .5rem;border-radius:100px;font-size:.55rem;font-weight:600;background:var(--v-bg);color:var(--v);border:1px solid var(--v3)}.mock-main{padding:1.25rem;display:flex;flex-direction:column;gap:.65rem}.mock-feed{background:#1E293B;border-radius:10px;padding:.75rem;font-family:'DM Sans',monospace;font-size:.6rem;color:var(--g2);line-height:1.8}.mock-feed-line{opacity:0;animation:fi .3s forwards}@keyframes fi{to{opacity:1}}.mock-job-card{background:var(--bg);border:1px solid var(--border);border-radius:10px;padding:.65rem .85rem;display:flex;justify-content:space-between;align-items:center;transition:all .2s}.mock-job-card:hover{border-color:var(--bh);box-shadow:0 2px 8px var(--gv)}.mock-job-title{font-size:.75rem;font-weight:700}.mock-job-co{font-size:.6rem;color:var(--t2);margin-top:.1rem}.mock-job-right{display:flex;align-items:center;gap:.4rem}.mock-badge{padding:.15rem .5rem;border-radius:100px;font-size:.55rem;font-weight:700;background:var(--g-bg);color:var(--g)}.mock-btn-sm{padding:.2rem .55rem;border-radius:6px;font-size:.55rem;font-weight:700;background:var(--v);color:#fff;border:none}
.steps-sect{padding:6rem 2rem;background:var(--bg2);border-top:1px solid var(--border);border-bottom:1px solid var(--border)}.steps-box{max-width:750px;margin:0 auto}.stp{display:flex;gap:1.5rem;padding-bottom:2.25rem}.stp:last-child{padding-bottom:0}.stp-left{display:flex;flex-direction:column;align-items:center;flex-shrink:0}.stp-num{width:42px;height:42px;border-radius:50%;background:linear-gradient(135deg,var(--v),#7C3AED);display:grid;place-items:center;font-weight:800;font-size:.95rem;color:#fff;box-shadow:0 4px 16px var(--gv)}.stp-line{width:2px;flex:1;background:linear-gradient(180deg,var(--v3),transparent);margin-top:.5rem;min-height:25px}.stp:last-child .stp-line{display:none}.stp-right{padding-top:.35rem}.stp-title{font-size:1.05rem;font-weight:700;margin-bottom:.3rem}.stp-text{color:var(--t2);font-size:.88rem;line-height:1.6}
.africa{padding:6rem 2rem;text-align:center;position:relative;overflow:hidden}.africa-glow{position:absolute;width:500px;height:500px;border-radius:50%;background:var(--o);filter:blur(200px);opacity:.04;top:50%;left:50%;transform:translate(-50%,-50%)}.africa-q{font-family:'Instrument Serif',serif;font-size:clamp(1.5rem,3.2vw,2.4rem);font-weight:400;line-height:1.35;max-width:700px;margin:0 auto 1.25rem;position:relative;z-index:1}.africa-q em{font-style:italic;color:var(--o)}.africa-sub{color:var(--t2);font-size:.92rem;line-height:1.7;max-width:520px;margin:0 auto 2.5rem;position:relative;z-index:1}
.foot{padding:2.5rem 2rem;border-top:1px solid var(--border);display:flex;justify-content:space-between;align-items:center;max-width:1200px;margin:0 auto;flex-wrap:wrap;gap:1rem}.foot-l{font-size:.75rem;color:var(--t3)}.foot-r{display:flex;gap:1.5rem}.foot-r a{color:var(--t3);text-decoration:none;font-size:.75rem;transition:color .2s}.foot-r a:hover{color:var(--t1)}
@media(max-width:900px){.feat-grid{grid-template-columns:1fr 1fr}.mockup-body{grid-template-columns:1fr}.mock-sidebar{display:none}}
@media(max-width:640px){.nav-mid{display:none}.feat-grid{grid-template-columns:1fr}.hero-metrics{flex-wrap:wrap;gap:1.5rem;justify-content:center}.hero-btns{flex-direction:column;align-items:center}.foot{justify-content:center;text-align:center}}
      `}</style>

      <nav className="nav"><Link href="/" className="nav-left"><div className="nav-mark">⚡</div><span className="nav-word">AutoApply</span></Link><div className="nav-mid"><a href="#features">Features</a><a href="#preview">Preview</a><a href="#how-it-works">How It Works</a><a href="https://github.com/chibuchi001/AutoApply" target="_blank" rel="noopener noreferrer">GitHub</a></div><Link href="/app" className="nav-go">Launch App →</Link></nav>

      <section className="hero" ref={hero.ref}><div className="hero-pattern"/><div className="hero-glow1"/><div className="hero-glow2"/><div className={`reveal ${hero.visible?'in':''}`}><div className="hero-chip"><span className="hero-chip-dot"/>Amazon Nova Hackathon 2026</div></div><h1 className={`hero-h1 reveal reveal-d1 ${hero.visible?'in':''}`}>Stop Applying.<br/><em>Start Getting Hired.</em></h1><p className={`hero-p reveal reveal-d2 ${hero.visible?'in':''}`}>An AI agent fleet that searches job boards, matches your skills, writes cover letters, applies for you, and coaches you through interviews — all powered by Amazon Nova.</p><div className={`hero-btns reveal reveal-d3 ${hero.visible?'in':''}`}><Link href="/app" className="btn-main">⚡ Get Started Free</Link><a href="https://github.com/chibuchi001/AutoApply" target="_blank" rel="noopener noreferrer" className="btn-ghost">✦ View Source</a></div><div className={`hero-metrics reveal reveal-d4 ${hero.visible?'in':''}`}><div className="metric"><div className="metric-val c-v">3+</div><div className="metric-lbl">Job Boards</div></div><div className="metric"><div className="metric-val c-o">34</div><div className="metric-lbl">Skills Parsed</div></div><div className="metric"><div className="metric-val c-g">5×</div><div className="metric-lbl">Faster Apply</div></div><div className="metric"><div className="metric-val c-b">100%</div><div className="metric-lbl">AI-Powered</div></div></div></section>

      <section className="logos" ref={powered.ref}><div className="logos-label">Built on Amazon Nova & AWS</div><div className={`logos-row reveal ${powered.visible?'in':''}`}>{[{name:'Nova Act',dot:'d-o'},{name:'Nova 2 Lite',dot:'d-v'},{name:'Nova 2 Sonic',dot:'d-g'},{name:'Bedrock',dot:'d-b'},{name:'Amazon S3',dot:'d-y'}].map(l=>(<div className="logo-pill" key={l.name}><div className={`logo-dot ${l.dot}`}/><span className="logo-name">{l.name}</span></div>))}</div></section>

      <section className="feat" id="features" ref={features.ref}><div className="eyebrow">Features</div><h2 className="sect-h">Your AI Career Team</h2><p className="sect-p">Three Nova models. Six capabilities. One mission: get you hired.</p><div className="feat-grid">{[{emoji:'🔍',name:'Parallel Search',desc:'Nova Act launches browser agents across Indeed, LinkedIn & Glassdoor simultaneously — extracting jobs in real time.',tag:'Nova Act',tc:'tag-o'},{emoji:'🎯',name:'Smart Matching',desc:'Nova 2 Lite scores every job 0–100, identifies skill gaps, and tells you exactly how to address them.',tag:'Nova 2 Lite',tc:'tag-v'},{emoji:'✍️',name:'Cover Letters',desc:'Unique, cliché-free cover letters tailored to each job — highlighting your most relevant experience.',tag:'Nova 2 Lite',tc:'tag-v'},{emoji:'🤖',name:'Auto-Apply',desc:'Nova Act fills forms, uploads your resume, and answers screening questions. CAPTCHAs are escalated to you.',tag:'Nova Act',tc:'tag-o'},{emoji:'🎙️',name:'Voice Coach',desc:'Nova 2 Sonic conducts mock interviews with real-time voice feedback, tailored to each specific role.',tag:'Nova 2 Sonic',tc:'tag-g'},{emoji:'📡',name:'Live Agent Feed',desc:'Watch every agent action via WebSocket streaming. Full transparency into what your AI is doing.',tag:'WebSocket',tc:'tag-b'}].map((f,i)=>(<div className={`feat-card reveal reveal-d${i+1} ${features.visible?'in':''}`} key={f.name}><span className="feat-emoji">{f.emoji}</span><div className="feat-name">{f.name}</div><div className="feat-desc">{f.desc}</div><span className={`feat-tag ${f.tc}`}>{f.tag}</span></div>))}</div></section>

      <section className="mockup-sect" id="preview" ref={mockup.ref}><div className="eyebrow">App Preview</div><h2 className="sect-h">See It In Action</h2><p className="sect-p">Real-time job search, matching, and application tracking</p><div className={`mockup-frame reveal ${mockup.visible?'in':''}`}><div className="mockup-bar"><div className="mockup-dot r"/><div className="mockup-dot y"/><div className="mockup-dot g"/><div className="mockup-url">auto-apply-beta.vercel.app/app</div></div><div className="mockup-body"><div className="mock-sidebar"><div className="mock-widget"><div className="mock-widget-title">📋 Resume Parsed</div><div style={{fontSize:'.65rem',color:'var(--t2)'}}>Experience: 3 yrs · Skills: 34</div><div className="mock-skill-row">{['Python','React','Node.js','FastAPI','TypeScript','AWS','Docker','PostgreSQL'].map(s=>(<span className="mock-skill" key={s}>{s}</span>))}</div></div><div className="mock-widget"><div className="mock-widget-title">🔍 Search Config</div><div style={{fontSize:'.65rem',color:'var(--t2)',lineHeight:1.8}}>Role: Smart Contract Developer<br/>Location: Lagos, Nigeria<br/>Platforms: LinkedIn<br/>Min Match: 40%</div></div></div><div className="mock-main"><div className="mock-feed">{[{time:'15:02',tag:'SEARCH',text:'Starting parallel search across 3 platforms...'},{time:'15:05',tag:'SEARCH',text:'Found 5 jobs across 1 platforms'},{time:'15:05',tag:'MATCH',text:'Analyzing match scores for 5 jobs...'},{time:'15:06',tag:'COVER',text:'Generating tailored cover letters...'},{time:'15:07',tag:'DONE',text:'Ready to apply to 5 matched jobs.'}].map((l,i)=>(<div className="mock-feed-line" key={i} style={{animationDelay:`${mockup.visible?i*0.4:0}s`}}><span style={{color:'#64748B'}}>{l.time}</span>{' '}<span style={{color:l.tag==='DONE'?'#34D399':l.tag==='SEARCH'?'#818CF8':'#FB923C'}}>[{l.tag}]</span>{' '}<span style={{color:'#CBD5E1'}}>{l.text}</span></div>))}</div>{[{title:'Senior Smart Contract Developer',co:'TechCorp Nigeria Ltd',score:'85%'},{title:'Mid-level Blockchain Engineer',co:'Fintech Solutions Africa',score:'72%'},{title:'Lead Web3 Developer',co:'Global Bank Nigeria',score:'68%'}].map(j=>(<div className="mock-job-card" key={j.title}><div><div className="mock-job-title">{j.title}</div><div className="mock-job-co">{j.co}</div></div><div className="mock-job-right"><span className="mock-badge">{j.score} match</span><span className="mock-btn-sm">Apply</span></div></div>))}</div></div></div></section>

      <section className="steps-sect" id="how-it-works" ref={steps.ref}><div className="eyebrow">How It Works</div><h2 className="sect-h">Four Steps to Your Next Job</h2><p className="sect-p">From resume upload to interview prep in under 5 minutes</p><div className="steps-box">{[{n:'1',t:'Upload Your Resume',d:'Drop your PDF and Nova 2 Lite extracts 34+ data points — skills, experience, education, contact info — instantly.'},{n:'2',t:'Set Your Preferences',d:'Choose your target role, location, platforms, and minimum match score. Toggle dry-run mode to test safely.'},{n:'3',t:'Watch Agents Work',d:'Nova Act browser agents search job boards in parallel. Each job gets a match score, gap analysis, and tailored cover letter.'},{n:'4',t:'Apply & Practice',d:"One-click apply with Nova Act. Then practice with Nova 2 Sonic's voice coach — tailored questions for each specific role."}].map((s,i)=>(<div className={`stp reveal reveal-d${i+1} ${steps.visible?'in':''}`} key={s.n}><div className="stp-left"><div className="stp-num">{s.n}</div><div className="stp-line"/></div><div className="stp-right"><div className="stp-title">{s.t}</div><div className="stp-text">{s.d}</div></div></div>))}</div></section>

      <section className="africa" ref={africa.ref}><div className="africa-glow"/><p className={`africa-q reveal ${africa.visible?'in':''}`}>A developer in Lagos with identical skills shouldn&apos;t lose opportunities because they can&apos;t spend <em>40 hours a week</em> on applications.</p><p className={`africa-sub reveal reveal-d1 ${africa.visible?'in':''}`}>AutoApply levels the playing field — giving every developer in Lagos, Nairobi, and Accra the same AI-powered tools as candidates in San Francisco.</p><div className={`reveal reveal-d2 ${africa.visible?'in':''}`}><Link href="/app" className="btn-main">⚡ Start Applying Now</Link></div></section>

      <footer className="foot"><span className="foot-l">AutoApply — Amazon Nova Hackathon 2026 · #AmazonNova</span><div className="foot-r"><a href="https://github.com/chibuchi001/AutoApply" target="_blank" rel="noopener noreferrer">GitHub</a><Link href="/app">Launch App</Link></div></footer>
    </div>
  );
}